# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6664666765c9e05f1a44fab2e9050cb9e8288d22baf5910e761d77b4880e143ca2324b806e4c61f0e0e27e8d596a4d84c4080b7fc09577f1c724149ebdd8f2b2

test:
  secret_key_base: 14968e8a2f99672d9794505c105e6db678be136e5e03eeaedd28d7a8d6944da9deb766d56373c34e925178578f2281ce66bad6688f9cb77cff7c3c9d455f6b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
